#! /bin/bash

FOUND_BROWSER=$(if [ -n `which google-chrome 2> /dev/null` ]; then
			echo `which google-chrome` 
		elif [ -n `which firefox 2> /dev/null` ]; then
			echo `which firefox` 
		fi)

export BROWSER=${BROWSER:-$FOUND_BROWSER}

exho $BROWSER

export ANACONDA=${ANACONDA:-$HOME/anaconda}

echo $ANACONDA

OS=`python  -mplatform | sed 's/-.*$//'`
PLATFORM_REQS=${OS,,}-requirements.txt

if [ ! -d $ANACONDA/envs/notebooks ]; then
	conda create --name notebooks --file $PLATFORM_REQS
fi

. activate notebooks

ipython notebook

# vim: se nowrap tw=0 :

